package generator

import (
	"archive/zip"
	"bytes"
	"database/sql"
	"fmt"
	"strings"
	"text/template"
	"time"

	"elko-project-wizard/internal/directive"
	"elko-project-wizard/internal/profile"

	"github.com/google/uuid"
)

// Request describes what to generate.
type Request struct {
	ProjectName string
	ProfileID   string
	Directives  []*directive.Directive
	Variables   map[string]interface{}
}

// Result is the generated zip bundle.
type Result struct {
	ID          string
	ProjectName string
	ZipBytes    []byte
	Files       []string
	CreatedAt   time.Time
}

// Generator builds project scaffolds from directives.
type Generator struct {
	db       *sql.DB
	dirStore *directive.Store
	profStore *profile.Store
}

func New(db *sql.DB) *Generator {
	return &Generator{
		db:        db,
		dirStore:  directive.NewStore(db),
		profStore: profile.NewStore(db),
	}
}

// Generate builds a zip scaffold from a profile.
func (g *Generator) Generate(profileID, projectName string) (*Result, error) {
	p, err := g.profStore.Get(profileID)
	if err != nil {
		return nil, fmt.Errorf("get profile: %w", err)
	}
	if projectName == "" {
		projectName = p.ProjectName
	}
	if projectName == "" {
		projectName = "my-project"
	}

	var directives []*directive.Directive
	for _, id := range p.DirectiveIDs {
		d, err := g.dirStore.Get(id)
		if err != nil {
			continue // skip missing directives gracefully
		}
		directives = append(directives, d)
	}

	req := &Request{
		ProjectName: projectName,
		ProfileID:   profileID,
		Directives:  directives,
		Variables:   p.Variables,
	}
	return g.build(req)
}

func (g *Generator) build(req *Request) (*Result, error) {
	buf := new(bytes.Buffer)
	zw := zip.NewWriter(buf)

	files := map[string]string{}

	// Always generate AGENTS.md and CLAUDE.md
	agentsMD, err := buildAgentsMD(req)
	if err != nil {
		return nil, fmt.Errorf("build AGENTS.md: %w", err)
	}
	files["AGENTS.md"] = agentsMD
	files["CLAUDE.md"] = "@AGENTS.md\n"

	// .gitignore based on tech stack
	files[".gitignore"] = buildGitignore(req)

	// Basic README
	files["README.md"] = buildReadme(req)

	// Dockerfile + docker-compose if docker directive selected
	if hasDirectiveCategory(req.Directives, "docker") {
		files["Dockerfile"] = buildDockerfile(req)
		files["docker-compose.yml"] = buildDockerCompose(req)
	}

	// Write all files into zip under project dir
	prefix := req.ProjectName + "/"
	var fileList []string
	for name, content := range files {
		path := prefix + name
		w, err := zw.Create(path)
		if err != nil {
			return nil, err
		}
		if _, err := w.Write([]byte(content)); err != nil {
			return nil, err
		}
		fileList = append(fileList, path)
	}

	if err := zw.Close(); err != nil {
		return nil, err
	}

	result := &Result{
		ID:          uuid.New().String(),
		ProjectName: req.ProjectName,
		ZipBytes:    buf.Bytes(),
		Files:       fileList,
		CreatedAt:   time.Now(),
	}

	// Persist generation record
	filesJSON := `["` + strings.Join(fileList, `","`) + `"]`
	g.db.Exec(`INSERT INTO generations (id,profile_id,project_name,files,created_at) VALUES (?,?,?,?,?)`,
		result.ID, req.ProfileID, req.ProjectName, filesJSON, result.CreatedAt)

	return result, nil
}

func buildAgentsMD(req *Request) (string, error) {
	tmpl := `# AGENTS.md — {{.ProjectName}}

> Generated by elko-project-wizard · {{.Date}}

This file provides directives for AI coding agents (Claude Code, OpenCode, Cursor, Zed).

---
{{range .Directives}}
{{.Content}}

---
{{end}}
`
	t, err := template.New("agents").Parse(tmpl)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	err = t.Execute(&buf, map[string]interface{}{
		"ProjectName": req.ProjectName,
		"Date":        time.Now().Format("2006-01-02"),
		"Directives":  req.Directives,
	})
	return buf.String(), err
}

func buildReadme(req *Request) string {
	return fmt.Sprintf("# %s\n\n> Generated by [elko-project-wizard](https://github.com/jsoprych/elko-project-wizard)\n\n## Getting Started\n\n```bash\n# Install dependencies\n# Run tests\n# Start the app\n```\n", req.ProjectName)
}

func buildGitignore(req *Request) string {
	base := "# Generated by elko-project-wizard\n*.db\n*.sqlite\n.DS_Store\nThumbs.db\n"
	if hasDirectiveCategory(req.Directives, "tech-stack") {
		stack := techStack(req.Directives)
		switch stack {
		case "go":
			base += "\n# Go\n/bin/\n*.test\n*.out\ncoverage.html\n"
		case "nodejs":
			base += "\n# Node.js\nnode_modules/\ndist/\n.env\n*.log\n"
		case "python":
			base += "\n# Python\n__pycache__/\n*.pyc\n.venv/\ndist/\n*.egg-info/\n"
		}
	}
	if hasDirectiveCategory(req.Directives, "docker") {
		base += "\n# Docker\n.docker-data/\n"
	}
	return base
}

func buildDockerfile(req *Request) string {
	stack := techStack(req.Directives)
	switch stack {
	case "go":
		return fmt.Sprintf(`# Multi-stage Go build
FROM golang:1.23-alpine AS builder
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o app ./cmd/...

FROM alpine:latest
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /build/app .
EXPOSE 8080
CMD ["./app"]
`)
	case "nodejs":
		return fmt.Sprintf(`FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
EXPOSE 3000
CMD ["node", "dist/index.js"]
`)
	case "python":
		return `FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
`
	default:
		return fmt.Sprintf("# Add your Dockerfile for %s here\n", req.ProjectName)
	}
}

func buildDockerCompose(req *Request) string {
	return fmt.Sprintf(`version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - app-data:/app/data
    restart: unless-stopped

volumes:
  app-data:
`)
}

func hasDirectiveCategory(dirs []*directive.Directive, cat string) bool {
	for _, d := range dirs {
		if d.Category == cat {
			return true
		}
	}
	return false
}

func techStack(dirs []*directive.Directive) string {
	for _, d := range dirs {
		if d.Category == "tech-stack" {
			// ID format: stack-go, stack-nodejs, stack-python, etc.
			parts := strings.SplitN(d.ID, "-", 2)
			if len(parts) == 2 {
				return parts[1]
			}
		}
	}
	return "unknown"
}
